name: hugo

on:
  schedule:
    - cron: "0 0 1 * *" # at 00:00 on day-of-month 1
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        run: |
          echo "Installing dependencies"
          npm install
          echo "Building and pushing"
          npm run build && npm run node
          echo "Done"
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --cached --quiet || git commit -m "Update README.md"
          git push origin main

      - name: update description
        if: success()
        uses: peter-evans/dockerhub-description@v2
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.USERNAME }}/hugo
